#!/usr/bin/env bash

set -e

DOTFILES="$HOME/i3wm-dotfiles"
TMP="$(mktemp -d)"

trap 'rm -rf "$TMP"' EXIT

[ ! -d "$DOTFILES" ] && { echo "❌ $DOTFILES not found. Clone the repo to $HOME first."; exit 1; }

cd "$DOTFILES"

echo "📦 Installing repo packages..."
sudo dnf install -y < pkg.list

echo "⚙️ Running post-install scripts..."
for script in post-install-scripts/*; do
    [ -x "$script" ] && "$script" || echo -e "\e[33m⚠ Script failed: $script\e[0m"
done

echo "📁 Installing dotfiles..."
while read -r rel; do
    [ -z "$rel" ] && continue

    src="$DOTFILES/$rel"
    dst="$HOME/$rel"

    if [ ! -e "$src" ]; then
        echo -e "\e[31m✖ Missing in repo: $rel\e[0m"
        continue
    fi

    if [ -e "$dst" ]; then
        echo -e "\e[33m⚠ Replacing $dst\e[0m"
        rm -rf "$dst"
    fi

    mkdir -p "$(dirname "$dst")"
    cp -a "$src" "$dst"

    echo -e "\e[32m✔ Installed $rel\e[0m"
done < "$DOTFILES/dotfile-paths"


echo -e "\n\n📦 Installing hblock systemd timer...\n"
curl -o '/tmp/hblock.#1' 'https://raw.githubusercontent.com/hectorm/hblock/v1.6.2/resources/systemd/hblock.{service,timer}' \
  && echo '16d547d11d1eff1cd7109ef8436a899f2e868992b8d9de757e65d4ab94f64fe7  /tmp/hblock.service' | shasum -c \
  && echo '79ecc28c13b2489400bd5ddc0ee61ddaf6c3225acb1d54b5cb4026f822ae60e8  /tmp/hblock.timer' | shasum -c \
  && sudo mv /tmp/hblock.{service,timer} /etc/systemd/system/ \
  && sudo chown root:root /etc/systemd/system/hblock.{service,timer} \
  && sudo chmod 644 /etc/systemd/system/hblock.{service,timer} \
  && sudo systemctl daemon-reload \
  && sudo systemctl enable hblock.timer \
  && sudo systemctl start hblock.timer \
  && hblock

echo -e "\n\n📦 Installing additional apps...\n"
echo -e "\e[33m⚠ Some of these may fail if the app is already installed or if there are issues with the install script. Check the output for details.\e[0m"

echo -e "\n\n📦 Installing Starship, AppImage Integrator, Lazy Weather, Lazy Snapper, Brave, VS Code, Viber, and AnyDesk...\n"
curl -sS https://starship.rs/install.sh | sh
curl -fsSL https://raw.githubusercontent.com/apapamarkou/appimage-integrator/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-weather/main/install | bash
curl -sSL https://raw.githubusercontent.com/apapamarkou/lazy-snapper/main/install | bash
curl -fsS https://dl.brave.com/install.sh | sh
sudo rpm --import -y https://packages.microsoft.com/keys/microsoft.asc &&
echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\nautorefresh=1\ntype=rpm-md\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" | sudo tee /etc/yum.repos.d/vscode.repo > /dev/null
sudo dnf update
sudo dnf install -y code
sudo dnf install -y https://download.cdn.viber.com/desktop/Linux/viber.rpm
sudo cat > /etc/yum.repos.d/AnyDesk-Fedora.repo << "EOF" 
[anydesk]
name=AnyDesk Fedora - stable
baseurl=http://rpm.anydesk.com/fedora/$basearch/
gpgcheck=1
repo_gpgcheck=1
gpgkey=https://keys.anydesk.com/repos/RPM-GPG-KEY
EOF
dnf install -y anydesk

pip install pulsemixer

echo "✅ Done!"
