[colors]
background = #282A2E
background-alt = #373B41
foreground = #C5C8C6
primary = #58a6ff
secondary = #58a6ff
alert = #A54242
disabled = #707880

[bar/example]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 1
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = "JetBrainsMono Nerd Font:size=14;2"

modules-left = xworkspaces i3mode xwindow
modules-right = weather filesystem pulseaudio xkeyboard freebsd-net memory cpu date systray control-center

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

wm-restack = i3

; override-redirect = true

[module/i3mode]
type = custom/script
exec = ~/.config/polybar/scripts/i3-mode.sh
tail = true

[module/systray]
type = internal/tray
format-margin = 8pt
tray-spacing = 8pt

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.background-alt}
label-active-underline= ${colors.primary}
label-active-padding = 1

label-occupied = %name%
label-occupied-padding = 1

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
label = %title:0:40:...%

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = "%{A3:terminal -t PulseMixer -c PulseMixer -l -s 80x10 -e pulsemixer /:}%percentage%%%{A}"

label-muted = muted
label-muted-foreground = ${colors.disabled}

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.primary}
label = %{A1:terminal -t TopWindow -c TopWindow -l -s 100x34 -e htop /:}%{A2:terminal -t TOP -c TOP -l -e htop:}%{A3:terminal -t TopWindow -c TopWindow -l -s 100x34 -e top /:} %percentage_used:2%%%{A}%{A}%{A}

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "󰍛 "
format-prefix-foreground = ${colors.primary}
label = %{A1:terminal -t TopWindow -c TopWindow -l -s 100x34 -e htop /:}%{A2:terminal -t TopWindow -c TopWindow -l -s 100x34 -e htop:}%{A3:terminal -t TopWindow -c TopWindow -l -s 100x34 -e top /:}%percentage:2%%%{A}%{A}%{A}

[module/freebsd-net]
type = custom/script
exec = ~/.config/polybar/scripts/network.sh
interval = 3
tail = false
click-left=terminal -c NetConfWindow -l -s 100x30 -e 'sudo bsdconfig networking'

[module/date]
type = internal/date
interval = 1

date = %a %d %b %H:%M

label = "%{A1:terminal -c CalcurseWindow -s 140x35 -e 'calcurse' /:}%date%%{A}"
label-foreground = ${colors.primary}

[settings]
screenchange-reload = true
pseudo-transparency = true

[module/weather]
type = custom/script
# Calls weather -m, but uses 'head' to keep it to one line if needed
exec = weather -m | head -n 1
# Update every 10 minutes (600 seconds)
interval = 600
format-prefix = "󰖐 "
format-prefix-foreground = #f9ae00
label = %output%
click-left = terminal -c weatherWindow -l -s 173x38 -e weather

[module/nightlight]
type = custom/script
exec = nightlight status
interval = 5
click-left = nightlight toggle
click-right = nightlight stop

[module/filesystem]
type = custom/script
interval = 25
exec = echo "/ $(df / | grep -oE '([0-9]+)%')"
click-right = terminal -c NcduWindow -l -s 100x30 -e ncdu
click-left = terminal -c FilesWindow -l -s 100x30 -e nnn
; vim:ft=dosini
